Global Enum $SIMONSAYS_VOWEL_NO, $SIMONSAYS_VOWEL_YES
Global Enum $SIMONSAYS_STRIKE_0, $SIMONSAYS_STRIKE_1, $SIMONSAYS_STRIKE_2
Global Enum $SIMONSAYS_RED, $SIMONSAYS_BLUE, $SIMONSAYS_GREEN, $SIMONSAYS_YELLOW
Global $aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES+1][$SIMONSAYS_STRIKE_2+1][$SIMONSAYS_YELLOW+1]
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_0][$SIMONSAYS_RED] = $SIMONSAYS_BLUE
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_1][$SIMONSAYS_RED] = $SIMONSAYS_RED
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_2][$SIMONSAYS_RED] = $SIMONSAYS_YELLOW

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_0][$SIMONSAYS_BLUE] = $SIMONSAYS_YELLOW
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_1][$SIMONSAYS_BLUE] = $SIMONSAYS_BLUE
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_2][$SIMONSAYS_BLUE] = $SIMONSAYS_GREEN

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_0][$SIMONSAYS_GREEN] = $SIMONSAYS_GREEN
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_1][$SIMONSAYS_GREEN] = $SIMONSAYS_YELLOW
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_2][$SIMONSAYS_GREEN] = $SIMONSAYS_BLUE

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_0][$SIMONSAYS_YELLOW] = $SIMONSAYS_RED
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_1][$SIMONSAYS_YELLOW] = $SIMONSAYS_GREEN
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_NO][$SIMONSAYS_STRIKE_2][$SIMONSAYS_YELLOW] = $SIMONSAYS_RED


$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_0][$SIMONSAYS_RED] = $SIMONSAYS_BLUE
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_1][$SIMONSAYS_RED] = $SIMONSAYS_YELLOW
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_2][$SIMONSAYS_RED] = $SIMONSAYS_GREEN

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_0][$SIMONSAYS_BLUE] = $SIMONSAYS_RED
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_1][$SIMONSAYS_BLUE] = $SIMONSAYS_GREEN
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_2][$SIMONSAYS_BLUE] = $SIMONSAYS_RED

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_0][$SIMONSAYS_GREEN] = $SIMONSAYS_YELLOW
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_1][$SIMONSAYS_GREEN] = $SIMONSAYS_BLUE
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_2][$SIMONSAYS_GREEN] = $SIMONSAYS_YELLOW

$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_0][$SIMONSAYS_YELLOW] = $SIMONSAYS_GREEN
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_1][$SIMONSAYS_YELLOW] = $SIMONSAYS_RED
$aSimonSaysAnswers[$SIMONSAYS_VOWEL_YES][$SIMONSAYS_STRIKE_2][$SIMONSAYS_YELLOW] = $SIMONSAYS_BLUE