Global Const $MEMORY_STAGE_COUNT = 5
Global Const $MEMORY_BUTTON_COUNT = 4
Global Enum $MEMORY_ACTION_LABEL_4 = 1, $MEMORY_ACTION_POSITION_1, $MEMORY_ACTION_POSITION_2, $MEMORY_ACTION_POSITION_3, $MEMORY_ACTION_POSITION_4, _
	$MEMORY_ACTION_POSITION_STAGE_1, $MEMORY_ACTION_POSITION_STAGE_2, $MEMORY_ACTION_LABEL_STAGE_1, $MEMORY_ACTION_LABEL_STAGE_2, _
	$MEMORY_ACTION_LABEL_STAGE_3, $MEMORY_ACTION_LABEL_STAGE_4
Global Const $aMemoryActions[$MEMORY_STAGE_COUNT][$MEMORY_BUTTON_COUNT]=[[$MEMORY_ACTION_POSITION_2,$MEMORY_ACTION_POSITION_2, $MEMORY_ACTION_POSITION_3, $MEMORY_ACTION_POSITION_4], _
	[$MEMORY_ACTION_LABEL_4, $MEMORY_ACTION_POSITION_STAGE_1, $MEMORY_ACTION_POSITION_1, $MEMORY_ACTION_POSITION_STAGE_1], _
	[$MEMORY_ACTION_LABEL_STAGE_2, $MEMORY_ACTION_LABEL_STAGE_1, $MEMORY_ACTION_POSITION_3, $MEMORY_ACTION_LABEL_4], _
	[$MEMORY_ACTION_POSITION_STAGE_1, $MEMORY_ACTION_POSITION_1, $MEMORY_ACTION_POSITION_STAGE_2, $MEMORY_ACTION_POSITION_STAGE_2], _
	[$MEMORY_ACTION_LABEL_STAGE_1, $MEMORY_ACTION_LABEL_STAGE_2, $MEMORY_ACTION_LABEL_STAGE_4, $MEMORY_ACTION_LABEL_STAGE_3]]
Global $aMemoryInputs[$MEMORY_STAGE_COUNT]
Global $iMemoryStageNumber = 1